using System;
using MongoDB.Bson.Serialization.Attributes;

namespace DataAccessLayer.Models
{
    public class Invoice
    {
        public Invoice(Guid invoiceId, string supplierId, decimal price)
        {
            InvoiceId = invoiceId;
            SupplierId = supplierId;
            Price = price;
        }

        [BsonId]
        // standard BSonId generated by MongoDb
        public Guid InvoiceId { get; set; }

        // external Id, easier to reference: 1,2,3 or A, B, C etc.
        public string SupplierId { get; set; }                          

        public decimal Price { get; set; } 
    }
}