using System;
using MongoDB.Bson.Serialization.Attributes;
using System.Buffers.Text;
using MongoDB.Driver;

namespace DataAccessLayer.Models
{
    public class Item
    {
        public Item(Guid itemId, string itemName )
        {
            ItemId = itemId;
            ItemName = itemName;
        }
        public Item()
        {
                
        }
        [BsonId]
        // standard BSonId generated by MongoDb
        public Guid ItemId { get; set; }
        
        public string ItemName { get; set; }
        
        public bool NeedFix { get; set; }
        
        public string BorrowedTo { get; set; }
    }
}