using System;
using System.Collections.Generic;
using MongoDB.Bson.Serialization.Attributes;
using Newtonsoft.Json;

namespace DataAccessLayer.Models
{
    public class Kit
    {
        public Kit(Guid kitId, string kitName)
        {
            KitId = kitId;
            KitName = kitName;
        }
        public Kit()
        {
        }
        [BsonId]
        // standard BSonId generated by MongoDb
        public Guid KitId { get; set; }

        // external Id, easier to reference: 1,2,3 or A, B, C etc.
        public string KitName { get; set; }
        public IEnumerable<Item> Items { get; set; }
    }
}